#!/bin/sh

CC=gcc
AR=ar
OUT="libzkcollection.a"
CFILES="src/proc/proc_base.c src/types/ztypes_base.c src/types/ztypes_mem.c src/types/ztypes_string.c"
CFILES="$CFILES src/extra/z_file.c src/extra/z_log.c src/extra/z_misc.c src/extra/z_sys.c src/extra/z_time.c"

CC -Os -O2 -c $CFILES
AR -q $OUT *.o
rm *.o

mkdir headers
cp src/*.h headers/
