#!/bin/sh

CC=gcc
AR=ar
OUT="libzkcollection.a"
CFILES="src/types/types/types_arr.c src/types/types/ztypes_dynt.c src/types/types/ztypes_irrg.c src/types/types/ztypes_mem.c src/types/types/ztypes_string.c"
CFILES="$CFILES src/imp/imp/z_file.c src/imp/imp/z_log.c src/imp/imp/z_misc.c src/imp/imp/z_sys.c src/imp/imp/z_time.c"

CC -Os -O2 -c $CFILES
AR -q $OUT *.o
rm *.o

mkdir headers
cp src/*.h headers/
