#ifndef ZAKAROUF__ZPREP_MAP_H
#define ZAKAROUF__ZPREP_MAP_H

#include "eval.h"

#define zpp__PRIV__MAP_END(...)
#define zpp__PRIV__MAP_OUT
#define zpp__PRIV__MAP_COMMA ,

#define zpp__PRIV__MAP_GET_END2() 0, zpp__PRIV__MAP_END
#define zpp__PRIV__MAP_GET_END1(...) zpp__PRIV__MAP_GET_END2
#define zpp__PRIV__MAP_GET_END(...) zpp__PRIV__MAP_GET_END1


#define zpp__PRIV__MAP_NEXT0(test, next, ...) next zpp__PRIV__MAP_OUT
#define zpp__PRIV__MAP_NEXT1(test, next) zpp__PRIV__MAP_NEXT0(test, next, 0)
#define zpp__PRIV__MAP_NEXT(test, next)  zpp__PRIV__MAP_NEXT1(zpp__PRIV__MAP_GET_END test, next)

#define zpp__PRIV__MAP0(f, x, peek, ...) f(x) zpp__PRIV__MAP_NEXT(peek, zpp__PRIV__MAP1)(f, peek, __VA_ARGS__)
#define zpp__PRIV__MAP1(f, x, peek, ...) f(x) zpp__PRIV__MAP_NEXT(peek, zpp__PRIV__MAP0)(f, peek, __VA_ARGS__)


#define zpp__PRIV__MAP_LIST_NEXT1(test, next) zpp__PRIV__MAP_NEXT0(test, zpp__PRIV__MAP_COMMA next, 0)
#define zpp__PRIV__MAP_LIST_NEXT(test, next)  zpp__PRIV__MAP_LIST_NEXT1(zpp__PRIV__MAP_GET_END test, next)

#define zpp__PRIV__MAP_LIST0(f, x, peek, ...) f(x) zpp__PRIV__MAP_LIST_NEXT(peek, zpp__PRIV__MAP_LIST1)(f, peek, __VA_ARGS__)
#define zpp__PRIV__MAP_LIST1(f, x, peek, ...) f(x) zpp__PRIV__MAP_LIST_NEXT(peek, zpp__PRIV__MAP_LIST0)(f, peek, __VA_ARGS__)



#define zpp__PRIV__MAP_PARTERN_NEXT()

#define zpp__PRIV__MAP_PARTERN0()
#define zpp__PRIV__MAP_PARTERN1() 

#define zpp__PRIV__MAP_PARTERN() zpp__PRIV__EVAL()

/*
 * Repeat function/ macro `f` equivalent to the vardic argument with each 
 * single argument is passed one-by-one at each repitation
 */
#define zpp__PRIV__MAP(f, ...) zpp__PRIV__EVAL(zpp__PRIV__MAP1(f, __VA_ARGS__, ()()(), ()()(), ()()(), 0))

/**
 * Same as MAP but each call is seperated by a comma.
 */
#define zpp__PRIV__MAP_LIST(f, ...) zpp__PRIV__EVAL(zpp__PRIV__MAP_LIST1(f, __VA_ARGS__, ()()(), ()()(), ()()(), 0))

//
#define zpp__PRIV__Args_map__Pattern__1(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix


#define zpp__PRIV__Args_map__Pattern__2(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__1(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__3(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__2(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__4(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__3(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))

#define zpp__PRIV__Args_map__Pattern__5(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__4(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__6(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__5(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__7(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__6(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__8(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__7(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__9(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__8(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__10(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__9(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__11(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__10(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__12(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__11(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__13(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__12(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__14(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__13(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__15(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__14(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__16(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__15(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__17(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__16(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__18(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__17(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__19(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__18(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__20(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__19(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__21(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__20(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__22(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__21(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__23(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__22(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__24(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__23(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__25(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__24(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__26(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__25(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__27(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__26(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__28(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__27(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__29(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__28(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__30(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__29(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__31(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__30(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__32(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__31(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__33(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__32(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__34(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__33(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__35(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__34(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__36(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__35(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__37(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__36(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__38(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__37(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__39(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__38(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__40(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__39(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__41(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__40(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__42(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__41(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__43(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__42(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__44(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__43(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__45(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__44(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__46(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__45(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__47(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__46(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__48(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__47(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__49(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__48(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__50(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__49(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__51(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__50(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__52(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__51(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__53(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__52(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__54(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__53(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__55(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__54(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__56(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__55(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__57(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__56(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__58(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__57(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__59(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__58(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__60(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__59(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__61(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__60(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__62(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__61(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__63(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__62(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__64(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__63(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__65(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__64(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__66(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__65(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__67(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__66(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__68(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__67(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__69(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__68(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__70(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__69(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__71(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__70(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__72(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__71(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__73(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__72(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__74(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__73(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__75(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__74(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__76(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__75(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__77(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__76(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__78(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__77(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__79(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__78(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__80(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__79(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__81(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__80(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__82(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__81(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__83(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__82(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__84(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__83(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__85(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__84(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__86(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__85(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__87(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__86(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__88(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__87(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__89(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__88(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__90(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__89(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__91(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__90(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__92(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__91(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__93(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__92(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__94(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__93(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__95(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__94(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__96(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__95(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__97(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__96(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__98(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__97(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__99(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__98(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__100(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__99(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__101(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__100(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__102(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__101(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__103(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__102(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__104(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__103(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__105(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__104(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__106(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__105(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__107(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__106(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__108(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__107(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__109(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__108(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__110(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__109(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__111(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__110(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__112(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__111(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__113(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__112(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__114(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__113(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__115(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__114(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__116(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__115(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__117(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__116(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__118(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__117(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__119(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__118(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__120(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__119(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__121(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__120(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__122(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__121(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__123(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__122(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__124(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__123(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__125(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__124(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__126(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__125(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__127(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__126(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__128(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__127(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__129(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__128(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__130(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__129(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__131(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__130(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__132(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__131(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__133(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__132(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__134(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__133(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__135(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__134(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__136(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__135(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__137(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__136(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__138(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__137(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__139(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__138(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__140(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__139(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__141(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__140(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__142(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__141(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__143(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__142(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__144(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__143(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__145(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__144(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__146(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__145(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__147(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__146(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__148(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__147(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__149(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__148(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__150(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__149(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__151(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__150(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__152(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__151(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__153(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__152(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__154(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__153(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__155(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__154(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__156(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__155(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__157(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__156(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__158(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__157(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_map__Pattern__159(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV__Args_map__Pattern__158(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))

#define zpp__PRIV__Args_map_Pattern(prefix, suffix, ...) zpp__CAT(zpp__PRIV__Args_map__Pattern__, zpp__Args_Count(__VA_ARGS__))(prefix, suffix, __VA_ARGS__)
//

#define zpp__PRIV__Args_maplist__Pattern__2(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_map__Pattern__1(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__3(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__2(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__4(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__3(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__5(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__4(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__6(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__5(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__7(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__6(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__8(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__7(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__9(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__8(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__10(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__9(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__11(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__10(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__12(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__11(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__13(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__12(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__14(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__13(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__15(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__14(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__16(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__15(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__17(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__16(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__18(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__17(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__19(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__18(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__20(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__19(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__21(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__20(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__22(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__21(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__23(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__22(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__24(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__23(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__25(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__24(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__26(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__25(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__27(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__26(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__28(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__27(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__29(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__28(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__30(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__29(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__31(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__30(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__32(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__31(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__33(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__32(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__34(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__33(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__35(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__34(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__36(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__35(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__37(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__36(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__38(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__37(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__39(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__38(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__40(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__39(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__41(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__40(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__42(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__41(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__43(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__42(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__44(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__43(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__45(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__44(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__46(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__45(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__47(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__46(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__48(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__47(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__49(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__48(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__50(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__49(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__51(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__50(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__52(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__51(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__53(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__52(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__54(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__53(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__55(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__54(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__56(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__55(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__57(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__56(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__58(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__57(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__59(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__58(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__60(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__59(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__61(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__60(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__62(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__61(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__63(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__62(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__64(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__63(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__65(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__64(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__66(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__65(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__67(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__66(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__68(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__67(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__69(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__68(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__70(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__69(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__71(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__70(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__72(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__71(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__73(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__72(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__74(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__73(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__75(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__74(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__76(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__75(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__77(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__76(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__78(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__77(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__79(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__78(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__80(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__79(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__81(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__80(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__82(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__81(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__83(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__82(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__84(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__83(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__85(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__84(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__86(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__85(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__87(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__86(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__88(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__87(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__89(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__88(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__90(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__89(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__91(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__90(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__92(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__91(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__93(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__92(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__94(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__93(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__95(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__94(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__96(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__95(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__97(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__96(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__98(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__97(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__99(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__98(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__100(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__99(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__101(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__100(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__102(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__101(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__103(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__102(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__104(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__103(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__105(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__104(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__106(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__105(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__107(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__106(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__108(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__107(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__109(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__108(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__110(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__109(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__111(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__110(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__112(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__111(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__113(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__112(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__114(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__113(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__115(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__114(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__116(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__115(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__117(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__116(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__118(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__117(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__119(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__118(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__120(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__119(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__121(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__120(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__122(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__121(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__123(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__122(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__124(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__123(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__125(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__124(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__126(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__125(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__127(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__126(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__128(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__127(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__129(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__128(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__130(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__129(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__131(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__130(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__132(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__131(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__133(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__132(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__134(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__133(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__135(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__134(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__136(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__135(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__137(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__136(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__138(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__137(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__139(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__138(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__140(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__139(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__141(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__140(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__142(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__141(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__143(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__142(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__144(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__143(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__145(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__144(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__146(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__145(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__147(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__146(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__148(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__147(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__149(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__148(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__150(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__149(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__151(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__150(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__152(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__151(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__153(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__152(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__154(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__153(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__155(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__154(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__156(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__155(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__157(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__156(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__158(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__157(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))
#define zpp__PRIV__Args_maplist__Pattern__159(prefix, suffix, ...) zpp__CAT(prefix, zpp__PRIV__Args_get_1(__VA_ARGS__)) suffix zpp__PRIV_COMMA() zpp__PRIV__Args_maplist__Pattern__158(prefix, suffix, zpp__Args_skip_1(__VA_ARGS__))

#define zpp__PRIV__Args_maplist_Pattern(prefix, suffix, ...) zpp__CAT(zpp__PRIV__Args_maplist__Pattern__, zpp__Args_Count(__VA_ARGS__))(prefix, suffix, __VA_ARGS__)


/*------------------------------------------*/
/*------------------------------------------*/

#define zpp__Args_map_Pattern(prefix, suffix, ...)     zpp__PRIV__Args_map_Pattern(prefix, suffix, __VA_ARGS__)
#define zpp__Args_maplist_Pattern(prefix, suffix, ...) zpp__PRIV__Args_maplist_Pattern(prefix, suffix, __VA_ARGS__)

#define zpp__Args_maplist(f, ...) zpp__PRIV__MAP_LIST(f, __VA_ARGS__)
#define zpp__Args_map(f, ...) zpp__PRIV__MAP(f, __VA_ARGS__)


#endif
