#ifndef ZAKAROUF__ZTYPES_H
#define ZAKAROUF__ZTYPES_H

#define ZAKAROUF__ZTYPES_VERSION_MAJOR 3
#define ZAKAROUF__ZTYPES_VERSION_MINOR 1
#define ZAKAROUF__ZTYPES_VERSION_PATCH 1

#include "ztypes/ztypes_ext.h"

#endif
