#ifndef ZAKAROUF__ZTYPES_H
#define ZAKAROUF__ZTYPES_H

#define ZAKAROUF__ZTYPES_VERSION_MAJOR 2
#define ZAKAROUF__ZTYPES_VERSION_MINOR 8
#define ZAKAROUF__ZTYPES_VERSION_PATCH 2

#include "ztypes/ztypes_ext.h"

#endif
