#ifndef ZAKAROUF__ZTYPES_H
#define ZAKAROUF__ZTYPES_H

#define ZAKAROUF__ZTYPES_VERSION_MAJOR 1
#define ZAKAROUF__ZTYPES_VERSION_MINOR 2
#define ZAKAROUF__ZTYPES_VERSION_PATCH 0

#include "ext.h"

#endif

