#ifndef ZAKAROUF__DYNAMIC_TYPE__CONFIG_H
#define ZAKAROUF__DYNAMIC_TYPE__CONFIG_H

#define Z___TYPE_INCLUED_CGLM

#define Z___TYPE_CONFIG__USE_TYPE_ARRAYS
	#define Z___TYPE_REALLOC_RESIZE_BY_DEFAULT 8

#define Z___TYPE_CONFIG__USE_VECTORS
	#define Z___TYPE_CONFIG__USE_TYPE_ARR_VECTOR
	//#define Z___TYPE_CONFIG__USE_f64_FOR_VECTOR_STRUCT
	//#define Z___TYPE_CONFIG__USE_i64_FOR_INT_VECTOR_STRUCT



#endif